[package]
name = "nevmes_market"
version = "0.5.0-alpha"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.23"
env_logger = "0.10.0"
nevmes_core = { path = "../nevmes-core" }
log = "0.4"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
